### ISSUE TITLE
Bestiary-Information-Page

### ISSUE THREAD

**Issue by Marcel-FR** [Marcel-FR/capstone-project#10]
## Value Proposition

- As a user,
- I want to be able to see all the details of the game's creatures in the Bestiary,
- so that I can easily reference them while playing the game.

## Description

![image](https://user-images.githubusercontent.com/121642717/222996985-ddc0d1bb-9be0-40b8-b8ad-f4b257388405.png)

## Acceptance Criteria

- Each creature has a detailed form with **all** of its relevant information.
- The value fields shouldn't be displayed if the monster doesn't have any value in it.
      

## Tasks

- [ ] Retrieve **all** the information for each creature from the .json files.
- [ ] Implement **all** the relevant fields and information.

**Comment by pung-one** [comment]
by "form" you mean "detail-page" i guess?
